#!/usr/bin/env bash

set -e

pip install --upgrade uv==0.9.6

uv venv --clear --python=3.13.2 homeassistant

source homeassistant/bin/activate

uv pip install -r requirements.test.txt

hass --config config --script ensure_config

if ! grep -R "logger" config/configuration.yaml >> /dev/null;then
echo "
logger:
  default: error
  logs:
    custom_components.ai_memory: debug
" >> config/configuration.yaml
fi
